---61) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE WORKING IN DEPTNO 10 AND 20?
SELECT * FROM EMP 
WHERE DEPTNO IN (10,20);


---62) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHO ARE WORKING AS MANAGER AND SALESMAN ?
SELECT * FROM EMP 
WHERE JOB IN ('MANAGER', 'SALESMAN');


---63) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SAL IS MORE THEN 1000 AND LESS THEN 5000 ?
SELECT * FROM EMP
WHERE SAL BETWEEN 1000 AND 5000;


---64) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE DEPTNO IS 20 AND WORKING AS MANAGER ?
SELECT * FROM EMP 
WHERE DEPTNO = 20 AND JOB = 'MANAGER';


---65) WAQTD ALL THE EMPLOYEE NAME AND SALARY WHO HIRED AFTER 81 INTO DEPTNO 10 ?
SELECT * FROM EMP 
WHERE HIREDATE > '31-DEC-81' AND DEPTNO = 10;


---66) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE NAME IS KING AND SCOTT ?
SELECT * FROM EMP 
WHERE ENAME IN ( 'KING', 'SCOTT');


---67) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SAL IS 3000 AND 5000 ?
SELECT * FROM EMP 
WHERE SAL IN (3000, 5000);


---68) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHO ARE WORKING IN DEPTNO 10 AS MANAGER AND HIRED ON ‘17-DEC-82 ?
SELECT * FROM EMP 
WHERE DEPTNO = 10 AND JOB = 'MANAGER' AND HIREDATE = '17-DEC-82';


---69) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE WORKING AS PRESIDENT IN DEPTNO 10 AND HAVING SALARY OF 5000 ?
SELECT * FROM EMP
WHERE JOB ='PRESIDENT' AND DEPTNO=10 AND SAL=5000;


---70) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WORKING IN DEPTNO 10,20 AS MANAGER ?
SELECT * FROM EMP 
WHERE DEPTNO IN (10,20) AND JOB = 'MANAGER';


---71) WAQTD ALL THE EMPLOYEES NAME AND JOB FOR  THE EMPLOYEES WHO HIRED AFTER 81 AND BEFORE 87 ?
SELECT * FROM EMP 
WHERE HIREDATE BETWEEN '01-JAN-82' AND '31-DEC-87';


---72) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SALARY ARE MORE THEN 1000 AND LESS THEN 5000 IN DEPTNO 20 ?
SELECT * FROM EMP 
WHERE SAL BETWEEN 1000 AND 5000 AND DEPTNO =20;


---73) WAQTD ALL THE DETAILS OF THE OF THE EMPLOYEES WHO ARE WORKING AS MANAGER IN DEPTNO 20 AND 10AND EARNING COMMISIONS 400,1600 ?
SELECT * FROM EMP 
WHERE DEPTNO IN ( 10,20) AND JOB = 'MANAGER' OR COMM IN ( 400,1600);


---74) WAQTD ENAME AND ANNAUL SALARY WITH ALISAS NAME FOR THE EMPLOYEES WHOSE ANNUAL SALARY IS MORE THEN 800 IN DEPTNO 30 WORKING   AS SALESMAN AND HIRED BEFORE THE 88 ?
SELECT * 
FROM ( SELECT EMP.*,SAL*12 "ANNUAL" FROM EMP )
WHERE ANNUAL>800 AND DEPTNO =30 AND JOB = 'SALESMAN' AND HIREDATE < '01-JAN-88';


---75) WAQTD ENAME AS A DEPTNO AS B AND JOB AS C FOR THE EMPLOYEES WHOSE COMM IS MORE THE 100 IN DEPTNO 10,20,30 ?
SELECT ENAME AS A , DEPTNO B, JOB "C" 
FROM EMP 
WHERE COMM >100 AND DEPTNO IN ( 10,20 ,30 ) ;


---76) WAQTD ALL THE DETAILS FOR THE EMPLOYEEES WHOSE HIREDATE ARE ‘03-DEC-81’ AND ‘17DEC-81’ I
NTO DEPTNO 30 ?
SELECT * FROM EMP 
WHERE DEPTNO =30 AND (HIREDATE = '03-DEC-81' OR HIREDATE = '17-DEC-81');


---77) WAQTD JOB AND SALARY FOR THE EMPLOYEES WHOSE COMM IS LESS THEN 2000 AND SALARIES ARE MORE THEN 1000 IN DEPTNO 10, 20?
SELECT JOB , SAL 
FROM EMP 
WHERE COMM < 2000 AND SAL > 1000 AND DEPTNO = 30 ;

 
---78) WAQTD ALL THE DEATILS  FOR THE EMPLOYEES WHOSE NAMES ARE KING AND SMITH AND ALLEN ?*/
SELECT * FROM EMP 
WHERE ENAME IN ('KING', 'SMITH','ALLEN');


---79) WAQTD ANNUAL SALARY HALF TERM SALARY WITH 25% DEDUCTION IN THE SALARY FOR THE EMPLOYEES WHOSE ANNUAL SALARY IS MORE THEN 6000 ?
SELECT * 
FROM ( SELECT EMP.*,SAL*12 "ANNUAL",SAL*6 "HALF_TERM", SAL-SAL*25/100 "25%_DEDUCT" FROM EMP)
WHERE ANNUAL >6000;


---80) ALL THE DETAILS AND HALF TERM SALARY FOR SALESMAN AND MANAGER IN DEPTNO 10,30 ?
SELECT EMP.*, SAL*6 "HALF_TERM" 
FROM EMP 
WHERE JOB IN ('SALESMAN' , 'MANAGER' ) AND DEPTNO IN ( 10,30);
