---81) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE WORKING IN DEPTNO 10 AND 20?
SELECT * FROM EMP 
WHERE DEPTNO IN ( 10,20);


---82) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHO ARE WORKING AS MANAGER AND SALESMAN ?
SELECT * FROM EMP 
WHERE JOB IN ('MANAGER' , 'SALESMAN');


---83) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SAL IS MORE THEN 1000 AND LESS THEN 5000 ?
SELECT * FROM EMP 
WHERE SAL BETWEEN 1000 AND 5000;


---84) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE DEPTNO IS 20 AND WORKING AS MANAGER ?
SELECT * FROM EMP 
WHERE DEPTNO = 20 AND JOB = 'MANAGER' ;


---85) WAQTD ALL THE EMPLOYEE NAME AND SALARY WHO HIRED AFTER 81 INTO DEPTNO 10 ?
SELECT * FROM EMP
WHERE HIREDATE < '31-DEC-81' AND DEPTNO IN 10 ;


---86) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE NAME IS KING AND SCOTT ?
SELECT * FROM EMP 
WHERE ENAME IN ('KING' , 'SCOTT');


---87) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SAL IS 3000 AND 5000 ?
SELECT * FROM EMP 
WHERE SAL IN (3000 , 5000);


---88) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHO ARE WORKING IN DEPTNO 10 AS MANAGER AND HIRED ON ‘17-DEC-82 ?
SELECT * FROM EMP 
WHERE DEPTNO IN 10 AND JOB IN 'MANAGER' AND HIREDATE IN '09-JUN-81';


---89) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE WORKING AS PRESIDENT IN DEPTNO 10 AND HAVING SALARY OF 5000 ?
SELECT * FROM EMP 
WHERE JOB IN 'PRESIDENT' AND DEPTNO IN 10 AND SAL IN 5000;


---90) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WORKING IN DEPTNO 10,20 AS MANAGER ?
SELECT * FROM EMP 
WHERE DEPTNO IN ( 10 ,20 ) AND JOB IN 'MANAGER';


---91) WAQTD ALL THE EMPLOYEES NAME AND JOB FRO THE EMPLOYEES WHO HIRED AFTER 81 AND BEFORE 87 ?
SELECT * FROM EMP 
WHERE HIREDATE BETWEEN '01-JAN-82' AND '31-DEC-86';


---92) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SALARY ARE MORE    THEN   1000 AND LESS THEN 5000 IN DEPTNO 20 ?
SELECT * FROM EMP 
WHERE (SAL BETWEEN 1000 AND 5000) AND DEPTNO IN 20 ;


---93) WAQTD ALL THE DETAILS OF THE OF THE EMPLOYEES WHO ARE WORKING AS MANAGER IN DEPTNO 20 AND 10AND EARNING COMMISIONS 400,1600 ?
SELECT * FROM EMP 
WHERE JOB IN 'MANAGER' AND DEPTNO IN (20 , 10) AND COMM IN (400 , 1600);


---94) WAQTD ENAME AND ANNAUL SALARY WITH ALISAS NAME FOR THE EMPLOYEES WHOSE ANNUAL SALARY IS MORE THEN 800 IN DEPTNO 30 WORKING AS SALESMAN AND HIRED BEFORE THE 88 ?
SELECT * 
FROM ( SELECT ENAME , JOB, SAL, SAL*12 "ANNUAL", DEPTNO, HIREDATE FROM EMP )
WHERE ANNUAL >800 AND DEPTNO IN 30 AND JOB IN 'SALESMAN' AND HIREDATE <'01-JAN-88';


---95) WAQTD ENAME AS A DEPTNO AS B AND JOB AS C FOR THE EMPLOYEES WHOSE COMM IS MORE THE 100 IN DEPTNO 10,20,30 ?
SELECT ENAME AS A , DEPTNO B , JOB "C" 
FROM EMP 
WHERE COMM > 100 AND DEPTNO IN ( 10, 20 ,30 ) ;


---96) WAQTD ALL THE DETAILS FOR THE EMPLOYEEES WHOSE HIREDATE ARE ‘03-DEC-81’ AND ‘17DEC-81’ INTO DEPTNO 30 ?
SELECT * FROM EMP 
WHERE HIREDATE IN ('03-DEC-81' , '17-DEC-81') AND DEPTNO IN 30 ;


---97) WAQTD JOB AND SALARY FOR THE EMPLOYEES WHOSE COMM IS LESS THEN 2000 AND SALARIES ARE MORE THEN 1000 IN DEPTNO 10, 20?
SELECT JOB , SAL , COMM 
FROM EMP 
WHERE COMM IS NULL AND SAL > 1000 AND DEPTNO IN (10,20 ) ;


---98) WAQTD ENAME FOR THE EMPLOYEES WHOSE NAMES ARE KING AND SMITH AND ALLEN ?
SELECT ENAME 
FROM EMP 
WHERE ENAME IN ( 'KING' , 'SMITH', 'ALLEN');


---99) WAQTD ANNUAL SALARY HALF TERM SALARY WITH 25% DEDUCTION IN THE SALARY FOR THE EMPLOYEES WHOSE ANNUAL SALARY IS MORE THEN 6000 ?
SELECT * 
FROM (SELECT EMP.* , SAL*12 "ANNUAL", SAL*6 "HALF-TERM" , SAL-SAL*25/100 "25%_DEDUCT" FROM EMP)
WHERE ANNUAL > 6000;


---100) ALL THE DETAILS AND HALF TERM SALARY FOR SALESMAN AND MANAGER IN DEPTNO 10,30 ?
SELECT * 
FROM ( SELECT EMP.*, SAL*6 "HALF-TERM" FROM EMP )
WHERE JOB IN ('SALESMAN' , 'MANAGER' ) AND DEPTNO IN (10,30);


---101) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHOSE HIRED BETWEEN 81 TO 89  INTO DEPTNO 20 ?
SELECT * FROM EMP 
WHERE (HIREDATE BETWEEN '01-JAN-81' AND '31-DEC-89') AND DEPTNO IN 20 ;


---102) WAQTD DETAILS FOR THE EMPLOYEES WHOSE SALARY IN THE RANGE OF 1000 TO 5000 IN DEPTNO 10,20 ?
SELECT * FROM EMP 
WHERE (SAL BETWEEN 1000 AND 5000) AND DEPTNO IN (10 , 20 ) ;


---103) WAQTD ENAME AND JOB FOR THE EMPLOYEES WHO ARE WORKING AS ANAGER AND EARNING COMMISION IN THE RANGE OF 100 TO 1000 ?
SELECT ENAME , JOB 
FROM EMP 
WHERE JOB IN 'SALESMAN' AND ( COMM BETWEEN 100 AND 1000);


---104) WAQTD ALL THE DEATILS ALONG WITH 3 MONTHS SALARY FOR THE EMPLOYEES WHOSE SALARY IS NOT NULL AND DOESNT HAVING ANY REPORTING MANAGER? */
SELECT EMP.*, SAL*3 "QUARTER_SAL"
FROM EMP 
WHERE SAL IS NOT NULL AND MGR IS NULL;


---106) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHO ARE EARNING SALARY ?
SELECT * FROM EMP 
WHERE SAL IS NOT NULL;


---107) WAQTD ANNAUL SALARY OF THE EMPLOYEE WHO ARE NOT EARNING COMMISSION ?
SELECT SAL*12 "ANNUAL" 
FROM EMP 
WHERE COMM IS NULL;


---108) WAQTD ALL THE DETAILS WITH ANNAUL COMMISSION FOR THE EMPLOYEE WHO  ARE WORKING IN DEPT 10 AND DONT HAVE ANY REPORTING MANAGER ?
SELECT EMP.*, COMM*12 "ANNUAL_COMM",
MGR FROM EMP 
WHERE DEPTNO IN 10 AND MGR IS NULL;


---109) WAQTD ALL THE DETAILS OF THE EMPLOYEE EXCEPT DEPTNO 10 AND WHO WHO HAVE REPORTING MAMAGER ?
SELECT * FROM EMP 
WHERE DEPTNO NOT IN 10 AND MGR IS NOT NULL;


---110) WAQTD ENAME AND SALARY. AND COMMISSION OF THE EMPLOYEE WHO EARNING COMMISSION IN DEPT NO 30 AND WORKING AS SALESMAN ?
SELECT ENAME , SAL, COMM 
FROM EMP 
WHERE COMM IS NOT NULL AND DEPTNO IN 30 AND JOB IN 'SALESMAN';


---111) WAQTD ENAME OF THE EMPLOYEE WHOSE NAME START WITH S ?
SELECT ENAME FROM EMP 
WHERE ENAME LIKE 'S%';


---112 ) WAQTD ALL THE DETAILS FOR THE EMPLOYEE WHOSE NAME ENDS WITH R ?
SELECT * FROM EMP 
WHERE ENAME LIKE '%R';

---113 ) WAQTD SALARY AND DEEPTNO AND NAME FOR THE EMPLOYEE WHOSE NAME HAVING A CHARACTER ?
SELECT ENAME , SAL , DEPTNO 
FROM EMP 
WHERE ENAME LIKE '%A%';


---114 ) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE HAVING 2 A IN THEIR NAME ?
SELECT * FROM EMP 
WHERE ENAME LIKE '%A%A%';


---115 ) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME HAVING CONJUGATIVE A IN THEIR NAMES ?
SELECT * FROM EMP 
WHERE REGEXP_LIKE (ENAME, '^.*A.*$','i');


---116) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME HAVING 2ND CHARACTER AS M ?
SELECT * FROM EMP 
WHERE ENAME LIKE '_M%';


---117) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME HAVING LAST 2ND CHAPTER AS E ?
SELECT * FROM EMP 
WHERE ENAME LIKE '%E_';


---118) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME START WITH M HAVING 4TH CHARACTER L AND ENDS WITH R ?
SELECT * FROM EMP 
WHERE ENAME LIKE 'M__L%R';


---119) WAQTD ALL THE DETAILS OF AN ALL THE EMPLOYEE WHO ARE EARNING 4 DOGIT OF SALARY AND NAMES STARTS WITH VOWELS ?
SELECT * FROM EMP 
WHERE (SAL LIKE '____') AND REGEXP_LIKE (ENAME,'^[A,E,I,O,U].*','i');


---120 ) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME STARTS WITH CONSONANTS. ?
SELECT * FROM EMP 
WHERE NOT REGEXP_LIKE (ENAME,'^[A,E,I,O,U].*','i');


---121) WAQTD ENAME AND HIREDATE OF ALL THE EMPLOYEE WHO HIRED IN THE MONTH OF DEC ?
SELECT ENAME,HIREDATE 
FROM EMP 
WHERE HIREDATE LIKE '%DEC%';


---122) WAQTD ALL THE DETAILS FOR THE EMPLOYEE WHO HIRED DURING 1981 ?
SELECT * FROM EMP 
WHERE REGEXP_LIKE (ENAME,'.*81$','i');


---123) WAQTD ALL THE DETAILS OF THE EMPLOYEE EXCEPT WHOSE NAME HAVING A ?
SELECT * FROM EMP 
WHERE ENAME NOT LIKE '%A%';


---124) WAQTD SALARY AND NAMES FOR THE EMPLOYEE WHOSE NAME START WITH S EXCEPT THE EMPLOYEE WHOSE SALARY. STARTS WITH 1 ?
SELECT ENAME, SAL 
FROM EMP 
WHERE (ENAME LIKE 'S%') AND NOT REGEXP_LIKE(SAL,'^1.*','i');


---125) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME HAVING 2 TIME CONSUGATIVE. A ?
SELECT * FROM EMP 
WHERE REGEXP_LIKE (ENAME,'.*A.*A.*','i');

