 ---71.WAQTD SMITHS REPORTING MANAGER'S NAME
 SELECT ENAME FROM EMP 
 WHERE EMPNO IN (SELECT MGR FROM EMP 
                    WHERE ENAME IN 'SMITH');


 ---72.WAQTD ADAMS MANAGER'S MANAGER NAME
 SELECT ENAME FROM EMP 
 WHERE EMPNO IN (SELECT MGR FROM EMP 
                    WHERE EMPNO IN (SELECT MGR FROM EMP 
                                 WHERE ENAME IN 'ADAMS'));


 ---73.WAQTD DNAME OF JONES MANAGER
 SELECT DNAME FROM DEPT 
 WHERE DEPTNO IN (SELECT DEPTNO FROM EMP 
                     WHERE EMPNO IN (SELECT MGR FROM EMP 
                                     WHERE ENAME IN 'JONES'));


 ---74.WAQTD MILLER'S MANAGER'S SALARY
 SELECT ENAME , SAL 
 FROM EMP 
    WHERE EMPNO IN (SELECT MGR FROM EMP 
                    WHERE ENAME IN 'MILLER');


 ---75.WAQTD LOC OF SMITH'S MANAGER'S MANAGER.
 SELECT LOC FROM DEPT 
    WHERE DEPTNO IN (SELECT DEPTNO FROM EMP 
                     WHERE EMPNO IN (SELECT MGR FROM EMP 
                                     WHERE EMPNO IN (SELECT MGR FROM EMP 
                                                     WHERE ENAME IN 'SMITH')));


 ---76.WAQT DNAME OF THE EMPLOYEES REPORTING TO BLAKE
 SELECT DNAME FROM DEPT 
    WHERE DEPTNO = ALL (SELECT DEPTNO FROM EMP 
                        WHERE MGR IN (SELECT EMPNO FROM EMP 
                                      WHERE ENAME IN 'BLAKE'));


 ---77.WAQTD NUMBER OF EMPLPOYEES REPORTING TO KING
 SELECT COUNT(*) FROM EMP 
    WHERE MGR IN (SELECT EMPNO FROM EMP 
                  WHERE ENAME IN 'KING');


 --- 78.WAQTD DETAILS OF THE EMPLOYEES REPORTING TO JONES
 SELECT * FROM EMP 
    WHERE MGR IN (SELECT EMPNO FROM EMP 
                  WHERE ENAME IN 'JONES');


 ---79.WAQTD ENAMES OF THE EMPLOYEES REPORTING TO BLAKE'S MANAGER
 SELECT ENAME FROM EMP 
    WHERE MGR IN (SELECT MGR FROM EMP 
                  WHERE ENAME IN 'BLAKE');


 ---80) NUMBER OF EMPLOYEES REPORTING TO FORD'S MANAGER
 SELECT COUNT(*) 
 FROM EMP 
    WHERE MGR IN (SELECT MGR FROM EMP 
                  WHERE ENAME IN 'FORD');

