 ---1) WAQTD ENAME AND DNAME FOR ALL THE EMPLOYEES ?
 SELECT ENAME , DNAME 
 FROM EMP INNER JOIN DEPT 
 ON EMP.DEPTNO IN DEPT.DEPTNO;


 ---2) WAQTD DNAME AND SAL FOR THE EMPLOYEES WHO ARE WORKING AS MANAGER ?
 SELECT DNAME , SAL 
 FROM EMP INNER JOIN DEPT 
 ON EMP.DEPTNO IN DEPT.DEPTNO
 WHERE JOB IN 'MANAGER';


 ---3) WAQTD SAL AND HIREDATE AND LOC FOR THE EMPLOYEES WHOSE NAME HAVING A CHARACTER IN THEIR NAME  ?
 SELECT SAL , HIREDATE , LOC 
 FROM EMP INNER JOIN DEPT 
 ON EMP.DEPTNO IN DEPT.DEPTNO 
 WHERE ENAME LIKE '%A%';

 
 ---4) WAQTD ALL THE DETAILS OF AN EMPLOYEE ALONG WITH LOC FOR AN EMPLOYEES  WHOSE SAL IS MORE THAN 2000 IN ACCOUNTING DEPARTMENT ?
 SELECT * 
 FROM EMP , DEPT 
 WHERE EMP.DEPTNO IN DEPT.DEPTNO 
 AND SAL>2000 AND DNAME IN 'ACCOUNTING';


 ---5) WAQTD DNAME AND SAL AND DEPTNO OF AN EMPLOYEES  WHOSE JOB IS PRESIDENT  IN DEPTNO 10 ?
 SELECT DNAME , SAL , DEPT.DEPTNO 
 FROM EMP , DEPT
 WHERE EMP.DEPTNO IN DEPT.DEPTNO 
 AND JOB IN 'PRESIDENT' AND DEPT.DEPTNO IN 10 ;


 ---6) WAQTD ENAME AND DEPTNO AND LOC FOR ALL THE EMPLOYEES  WHOSE NAME ENDS  WITH VOWELS ?
 SELECT ENAME , DEPT.DEPTNO , LOC 
 FROM EMP INNER JOIN DEPT 
 ON EMP.DEPTNO IN DEPT.DEPTNO 
 WHERE REGEXP_LIKE (EMP.ENAME, '.*[A,E,I,O,U]$','i');


 ---7) WAQTD HIREDATE AND DEPTNO FOR ALL THE EMPLOYEES WHO  ARE WORKING IN  NEW YORK AND HAVING COMM ?
 SELECT HIREDATE , EMP.DEPTNO 
 FROM EMP INNER JOIN DEPT 
 ON EMP.DEPTNO IN DEPT.DEPTNO 
 WHERE LOC IN 'NEW YORK' AND COMM IS NOT NULL;


 ---8) WAQTD EMPLOYEE NAME AND DEPARTMENT NAME FOR ALL THE EMPLOYEE WHO  ARE HIRED IN THE MONTH OF FEB INTO ACCOUNTING  DEPARTMENT ?
 SELECT ENAME , DNAME 
 FROM EMP INNER JOIN DEPT 
 ON EMP.DEPTNO IN DEPT.DEPTNO
 WHERE HIREDATE LIKE '%-FEB-%' AND DNAME IN 'ACCOUNTING';


 ---9) WAQTD LOC AND EMPNO AND MGR NO FOR ALL THE EMPLOYEES  WHOSE SAL LESS THEN 5000 IN BOSTON HIRED IN THE YEAR OF 87 ?
 SELECT LOC , EMPNO , MGR 
 FROM EMP INNER JOIN DEPT 
 ON EMP.DEPTNO IN DEPT.DEPTNO 
 WHERE SAL < 5000 AND LOC IN 'BOSTON' AND (HIREDATE BETWEEN '01-JAN-87' AND '31-DEC-87');


 ---10) WAQTD DNAME AND LOC ALONG WITH 10% HIKE IN THE  SALARY OF AN EMPLOYEE   WHO ARE REPORTING TO ALLEN ?
 SELECT DNAME , LOC , SAL+SAL*10/100 "10% HIKE" 
 FROM EMP INNER JOIN DEPT 
 ON EMP.DEPTNO IN DEPT.DEPTNO 
 WHERE MGR IN (SELECT EMPNO FROM EMP 
               WHERE ENAME IN 'ALLEN');


 ---11) WAQTD ANNAUL SALARY AND LOC OF AN EMPLOYEE  WHOSE MANAGER NAME IS KING ?
 SELECT LOC , SAL*12 
 FROM EMP INNER JOIN DEPT 
 ON EMP.DEPTNO IN DEPT.DEPTNO 
 WHERE MGR IN (SELECT EMPNO FROM EMP
               WHERE ENAME IN 'KING');


 ---12) WAQTD ALL TEH DETAILS OF AN EMPLOYEES AND THEIR DNAME AND  LOC  FOR  THE EMPLOYEE WHOSECOMM IS NULL IN DEPTNO 10,20  ?
 SELECT EMP.* , LOC , DNAME 
 FROM EMP INNER JOIN DEPT 
 ON EMP.DEPTNO IN DEPT.DEPTNO
 WHERE COMM IS NULL AND EMP.DEPTNO IN (10 , 20 );


 ---13) WAQTD DNAME AND ENAME FOR THE EMPLOYEE WHOSE SALARY ENDS  WITH 50  IN DEPTNO 10,20,30 AND WORKING IN RESEARCH DEPARTMENT ?
 SELECT DNAME , ENAME 
 FROM EMP INNER JOIN DEPT 
 ON EMP.DEPTNO IN DEPT.DEPTNO 
 WHERE SAL LIKE '%50' AND EMP.DEPTNO IN (10,20,30) AND DNAME IN 'RESEARCH';


 ---14) WAQTD LOC DNAME  AND ENAME OF AN EMPLOYEES WHO  ARE HIRED BEFORE THE LAST TWO EMPLOYEES?
 SELECT LOC , DNAME , ENAME 
 FROM EMP INNER JOIN DEPT 
 ON EMP.DEPTNO IN DEPT.DEPTNO 
 WHERE HIREDATE <(SELECT MAX(HIREDATE) FROM EMP
                  WHERE HIREDATE < (SELECT MAX(HIREDATE) FROM EMP ));


 ---15) WAQTD DNAME AND SALARY OF AN EMPLOYEE WHOSE  NAME ENDS WITH CONSONANTS ?
 SELECT DNAME , SAL 
 FROM EMP INNER JOIN DEPT 
 ON EMP.DEPTNO IN DEPT.DEPTNO 
 WHERE NOT REGEXP_LIKE (EMP.ENAME ,'.*[A,E,I,O,U]$','i');


 ---16) WAQTD MGR SAL AND DEPTNO AND LOC OF AN EMPLOYEES WHOSE LOC ENDS WITH S ?
 SELECT MGR , SAL , EMP.DEPTNO , LOC 
 FROM EMP INNER JOIN DEPT 
 ON EMP.DEPTNO IN DEPT.DEPTNO 
 WHERE LOC LIKE '%S';


 ---17) WAQTD EMPNO AND LOC FOR THE EMPLOYEES WHOSE HIREDATE IS '01-JAN-81' IN DALLAS ?
 SELECT EMPNO , LOC 
 FROM EMP INNER JOIN DEPT 
 ON EMP.DEPTNO IN DEPT.DEPTNO 
 WHERE HIREDATE IN '01-JAN-81' AND LOC IN 'DALLAS';


 ---18) WAQTD ENAME AND LOC AND SAL OF AN EMPLOYES WHOSE EMPNO ARE 7369,7488 ?
 SELECT ENAME , LOC , SAL 
 FROM EMP INNER JOIN DEPT 
 ON EMP.DEPTNO IN DEPT.DEPTNO
 WHERE EMPNO IN (7369,7488);

 
---19) WAQTD ENAME AND LOC FOR THE EMPLOYEES WHOSE SAL IS LESS THEN KING  AND MORE THEN SMITH IN DEPTNO 30 AND WORKING IN SALES DEPARTMENT ?
 SELECT ENAME , LOC 
 FROM EMP INNER JOIN DEPT 
 ON EMP.DEPTNO IN DEPT.DEPTNO 
 WHERE SAL < (SELECT SAL FROM EMP 
              WHERE ENAME IN 'KING')
 AND SAL > (SELECT SAL FROM EMP 
            WHERE ENAME IN 'SMITH') 
 AND EMP.DEPTNO IN 30 
 AND JOB IN 'SALESMAN';


 ---20) WAQTD COMM AND LOC FOR THE EMPLOYEES WHOSE MGR IS 7902 WORKING IN  ACCOUNTING AND RESEARCH DEPARTMENT ?
 SELECT COMM , LOC 
 FROM EMP INNER JOIN DEPT 
 ON EMP.DEPTNO IN DEPT.DEPTNO 
 WHERE MGR IN 7902 
 AND DNAME IN ('ACCOUNTING' , 'RESEARCH');

 ---21) Display all students along with their trainer name and subject.
 SELECT STUDENT.* , TRAINER_NAME , SUBJECT 
 FROM STUDENT INNER JOIN TRAINER 
 ON STUDENT.TRAINER_ID IN TRAINER.TRAINER_ID ;

 ---22) Display student name, course, and trainer salary.
 SELECT STUDENT_NAME , COURSE , SALARY 
 FROM STUDENT , TRAINER 
 WHERE STUDENT.TRAINER_ID IN TRAINER.TRAINER_ID;


 ---23) Display all trainers and the students under them.
 SELECT TRAINER_NAME , STUDENT_NAME 
 FROM STUDENT INNER JOIN TRAINER 
 ON STUDENT.TRAINER_ID IN TRAINER.TRAINER_ID ;


 ---24) Display trainer name and total number of students under each trainer.
 SELECT TRAINER_NAME , COUNT(STUDENT_ID) 
 FROM STUDENT , TRAINER 
 WHERE STUDENT.TRAINER_ID IN TRAINER.TRAINER_ID 
 GROUP BY TRAINER_NAME ;


 ---25) Display students who are learning SQL along with trainer experience.
 SELECT STUDENT_NAME , TRAINER_NAME , EXPERIENCE_YRS
 FROM STUDENT , TRAINER 
 WHERE STUDENT.TRAINER_ID IN TRAINER.TRAINER_ID 
 AND COURSE IN 'SQL';


 ---26) Display students whose trainer has more than 5 years of experience.
 SELECT STUDENT_NAME , TRAINER_NAME , EXPERIENCE_YRS
 FROM STUDENT , TRAINER 
 WHERE STUDENT.TRAINER_ID IN TRAINER.TRAINER_ID 
 AND EXPERIENCE_YRS > 5 ;


 ---27) Display students whose trainer salary is greater than 60,000.
 SELECT STUDENT_NAME , TRAINER_NAME , SALARY 
 FROM STUDENT , TRAINER 
 WHERE STUDENT.TRAINER_ID IN TRAINER.TRAINER_ID 
 AND SALARY > 60000;


 ---28) Display trainers who train students from Pune.
 SELECT TRAINER_NAME , CITY 
 FROM STUDENT , TRAINER 
 WHERE STUDENT.TRAINER_ID IN TRAINER.TRAINER_ID 
 AND CITY IN 'Pune';


 ---29) Display trainers who teach Power BI and their students.
 SELECT TRAINER_NAME , SUBJECT , STUDENT_NAME 
 FROM STUDENT , TRAINER 
 WHERE STUDENT.TRAINER_ID IN TRAINER.TRAINER_ID 
 AND SUBJECT IN 'Power BI';


 ---30) Display trainer who has maximum number of students.
 SELECT TRAINER_NAME , COUNT(*) "STUDENTS"
 FROM TRAINER INNER JOIN STUDENT 
 ON TRAINER.TRAINER_ID = STUDENT.TRAINER_ID
 GROUP BY TRAINER_NAME 
 HAVING COUNT(*) >=ALL (SELECT COUNT(*) FROM STUDENT 
                        GROUP BY TRAINER_ID);


 ---31) Display trainer whose students joined most recently.
 SELECT DISTINCT T.TRAINER_NAME,S.JOIN_DATE
 FROM TRAINER T INNER JOIN STUDENT S
 ON T.TRAINER_ID = S.TRAINER_ID
 WHERE S.JOIN_DATE = (SELECT MAX(JOIN_DATE)FROM STUDENT);


 ---32) Display trainers whose average student fees is greater than 18,000.
 SELECT T.TRAINER_NAME , AVG(S.FEES)
 FROM TRAINER T INNER JOIN STUDENT S
 ON T.TRAINER_ID = S.TRAINER_ID 
 GROUP BY TRAINER_NAME 
 HAVING AVG(S.FEES) > 18000;


 ---33) Display students trained by SQL trainers.
 SELECT STUDENT_NAME , COURSE, TRAINER_NAME 
 FROM STUDENT S INNER JOIN TRAINER T 
 ON S.TRAINER_ID = T.TRAINER_ID 
 WHERE S.TRAINER_ID IN (SELECT TRAINER_ID FROM TRAINER 
                         WHERE SUBJECT IN 'SQL');


 ---34) Display trainers who have students from Mumbai.
 SELECT TRAINER_NAME , CITY 
 FROM STUDENT S INNER JOIN TRAINER T 
 ON S.TRAINER_ID = T.TRAINER_ID 
 WHERE CITY = 'Mumbai';


 ---35) Display trainers who teach students paying more than average fees.
 SELECT DISTINCT T.TRAINER_NAME FROM TRAINER T JOIN STUDENT S 
 ON S.TRAINER_ID = T.TRAINER_ID 
 WHERE S.FEES > (SELECT AVG(FEES) FROM STUDENT);




