 ---1) WAQTD ENAME AND DNAME FOR ALL THE EMPLOYEES OF THE EMPLOYEES NOT WORKING IN ANY DEPARTMENT ?
 SELECT ENAME , DNAME 
 FROM EMP LEFT JOIN DEPT 
 ON EMP.DEPTNO = DEPT.DEPTNO 
 WHERE EMP.DEPTNO IS NULL;


 ---2) WAQTDALL THE DETAILS OF AMPLOYEES AND THEIR DEPARTMENT DETAILS IF THE DEPARTMENT IN WHICH NO EMPLOYEES ARE WORKING ?
 SELECT * 
 FROM EMP RIGHT JOIN DEPT
 ON EMP.DEPTNO = DEPT.DEPTNO
 WHERE EMP.DEPTNO IS NULL;


 ---3) WAQTD ALL THE DETAILS OF AN EMPLOYEES AND HIER DEPARTMENT DETAILS IF THE EMPLOYEES NOT WORKING IN ANY DEPARTMENT AND THE DEPARTMENT IN WHICH THE NO EMPLOYEES ARE  WORKING ?
 SELECT * 
 FROM EMP FULL JOIN DEPT
 ON EMP.DEPTNO = DEPT.DEPTNO
 WHERE EMP.DEPTNO IS NULL;


 ---4) WAQTD ENAME AND SAL AND DNAME FOR THE EMPLOYEES THOSE WHO ARE NOT WORKING IN ANY DEPARTMENT ?
 SELECT ENAME , SAL , DNAME
 FROM EMP LEFT JOIN DEPT
 ON EMP.DEPTNO = DEPT.DEPTNO
 WHERE EMP.DEPTNO IS NULL;


 ---5) WAQTD HIERDATE AND JOB INCLUDING DNAME AND LOC FOR THE DEPARTMENT IN WHICH NO EMPLOYEES ARE WORKING  ?
 SELECT HIREDATE, JOB, DNAME, LOC
 FROM EMP RIGHT JOIN DEPT 
 ON EMP.DEPTNO = DEPT.DEPTNO
 WHERE EMP.DEPTNO IS NULL;


 ---6) WAQTD DNAME AND LOC AND JOB FOR THE EMPLOYEES WHO ARE NOT WORKING IN ANY DEPARTMENT AND THE DEPARTMENT NO EMPLOYEES ARE WORKING ?
 SELECT DNAME , LOC , JOB 
 FROM EMP FULL JOIN DEPT 
 ON EMP.DEPTNO = DEPT.DEPTNO
 WHERE EMP.DEPTNO IS NULL;


 ---7) WAQTD EMPLOYEES NAME AND DEPTNAME FOR ALL THE EMPLOYEES WHOSE SALARIES ARE MORE THEN 2000 ?
 SELECT ENAME , DNAME 
 FROM EMP LEFT JOIN DEPT 
 ON EMP.DEPTNO = DEPT.DEPTNO
 WHERE SAL > 2000;


 ---8) WAQTDMANAGER NAME AND THE EMPLOYEES SALARY FOR ALL THE EMPLOYEES THOSE WHO ARE WORKING IN DEPTNO 10,20 ?
 SELECT E2.ENAME , E2.SAL 
 FROM EMP E1 , EMP E2 
 WHERE E1.MGR = E2.EMPNO;


 ---9)WAQTD MANAGERS MANAGER NAME FOR ALL THE MANAGER WHOSE SALARIES ARE LESS THEN EMPLOYES ?
 SELECT E3.ENAME 
  FROM EMP E1,EMP E2, EMP E3
 WHERE E1.MGR= E2.EMPNO
 AND E2.MGR = E3.EMPNO
 AND E3.SAL < E1.SAL;


 ---10) WAQTD EMPLOYEES NAME MANAGER SALARY AND MANAGER MANAGE COMM FOR ALL THE MANAGER WHO HIRED BEFORE THE 87 AS SALESMAN AND EARNING SALARY MORE THEN MANAGERS MANAGER ?
 SELECT E1.ENAME,E2.SAL,E3.COMM
 FROM EMP E1,EMP E2, EMP E3
 WHERE E1.MGR = E2.EMPNO AND E2.MGR = E3.EMPNO
 AND E2.HIREDATE < '01-JAN-87' 
 AND E2.JOB IN 'SALESMAN'
 AND E2.SAL > E3.SAL;


 ---11) WAQTD ENAME AND MANAGER HIREDATE AND JOB FOR ALL THE EMPLOYEES WHO ARE WORKING IN NEW YORK ?
 SELECT E1.ENAME "EMPLOYEE", E2.HIREDATE "M_HIREDATE", E1.JOB "EMP_JOB"
 FROM EMP E1, EMP E2, DEPT D1
 WHERE E1.MGR = E2.EMPNO AND E1.DEPTNO = D1.DEPTNO
 AND D1.LOC IN 'NEW YORK';


 ---12) WAQTD EMPLOYEES DNAME AND MANAGER LOC INCLUDING EMPLOYEES SALARY AND MANAGER DEPTNO FOR ALL THE EMPLOYEES WHO ARE HIRED BEFORE THE MANAGERS MANAGE ?
 SELECT D1.DNAME "E_DEPT", D2.LOC "M_LOC", E1.SAL "E_SAL", E2.DEPTNO "M_DEPTNO"
 FROM EMP E1, EMP E2, DEPT D1, DEPT D2, EMP E3
 WHERE E1.MGR = E2.EMPNO AND E1.DEPTNO = D1.DEPTNO AND E2.DEPTNO = D2.DEPTNO AND E2.MGR = E3.EMPNO
 AND E1.HIREDATE < E3.HIREDATE;


 ---13) WAQTD MANAGERS MANAGER NAME FOR ALL THE EMPLOYEES WHO ARE WORKING IN MANAGERS LOCATION AND NOT WORKING IN MANAGES MANAGERS LOCATION ?
 SELECT E3.ENAME 
 FROM EMP E1, EMP E2, EMP E3, DEPT D3, DEPT D1, DEPT D2
 WHERE E1.MGR = E2.EMPNO AND E1.DEPTNO = D1.DEPTNO AND E2.DEPTNO = D2.DEPTNO AND
 E2.MGR = E3.EMPNO
 AND D1.LOC = D2.LOC 
 AND D1.LOC <> D3.LOC;


 ---14) WAQTD MANAGER NAME FOR THE MANAGERS MANAGER WHO ARE WORKING IN DEPTNO 20 AS ACTUAL MANAGER AND EARNING SALARY MORE THEN THE EMPLOYEES ?
 SELECT E2.ENAME 
 FROM EMP E1, EMP E2, EMP E3 
 WHERE E1.MGR = E2.EMPNO AND E2.MGR = E3.EMPNO 
 AND E3.DEPTNO = 20 
 AND E3.JOB = 'MANAGER'
 AND E3.SAL > E1.SAL;


 ---15) WAQTD MANAGERS DNAME AND MANAGERS MANAGER LOC FOR THE EMPLOYEES WHO ARE WORKING IN BOSTON ?
 SELECT D2.DNAME "M_DNAME", D3.LOC "MM_LOC"
 FROM EMP E1, EMP E2, EMP E3, DEPT D1, DEPT D2, DEPT D3
 WHERE E1.MGR = E2.EMPNO AND E1.DEPTNO = D1.DEPTNO AND E2.DEPTNO = D2.DEPTNO AND
 E2.MGR = E3.EMPNO AND D3.LOC IN 'BOSTON';


 ---16) WAQTD EMPLOYEES DNAME FOR THE MANAGERS MANAGER WHOSE SAL ARE MORE THAN MANAGER AND LESS THAN EMPLOYEES ?
 SELECT D1.DNAME "E_DNAME"
 FROM EMP E1, EMP E2, EMP E3, DEPT D1
 WHERE E1.MGR = E2.EMPNO AND E2.MGR = E3.EMPNO AND E1.DEPTNO = D1.DEPTNO
 AND E3.SAL > E2.SAL 
 AND E3.SAL < E1.SAL;


 ---17) WAQTD EMPLOYEES LOC AND MANAGERS MANAGERS LOC FOR THE MANAGER WHO ARE HIRED BEFORE THE EMPLOYEE AND EARNING SALARY MORE THAN THE EMPLOYEES ?
 SELECT D1.LOC "E_LOC", D3.LOC "MM_LOC"
 FROM EMP E1, EMP E2, EMP E3, DEPT D1, DEPT D3
 WHERE E1.MGR = E2.EMPNO AND E2.MGR = E3.EMPNO AND D1.DEPTNO = E1.DEPTNO AND D3.DEPTNO = E3.DEPTNO
 AND E2.HIREDATE < E1.HIREDATE 
 AND E2.SAL > E1.SAL;


 ---18) WAQTD DNAME FOR THE EMPLOYEES WHO HIRED BEFORE  THE MANAGERS INTO ACCOUNTING DEPARTMENT IN THE MONTH OF DEC ?
 SELECT D1.DNAME
 FROM EMP E1, EMP E2, DEPT D1
 WHERE E1.MGR=E2.EMPNO AND D1.DEPTNO=E1.DEPTNO
 AND E1.HIREDATE < E2.HIREDATE
 AND D1.DNAME='ACCOUNTING'
 AND E1.HIREDATE LIKE '%-DEC-%';


 ---19) WAQTD MANAGERS MANAGERS MANAGERS MANAGER NAME IF THEY ARE HIRED AFTER THE MANAGERS INTO DALLAS ?
 SELECT E5.ENAME 
 FROM EMP E1, EMP E2, EMP E3, EMP E4, EMP E5, DEPT D5
 WHERE E1.MGR=E2.EMPNO AND E2.MGR=E3.EMPNO AND E3.MGR=E4.EMPNO AND E4.MGR=E5.EMPNO
 AND D5.DEPTNO=E5.DEPTNO
 AND E5.HIREDATE > E2.HIREDATE
 AND D5.LOC = 'DALLAS';


 ---20)WAQTD ENAME ,LOC , AND SAL OF ALL THE EMPLOYEES EVEN IF THEY NOT ASSIGNED TO ANY DEPARTMENT . WORKING AS SALESMAN AND EARNING SALARY MORE THEN 1000 ?
 SELECT ENAME, LOC, SAL
 FROM EMP LEFT JOIN DEPT 
 ON EMP.DEPTNO = DEPT.DEPTNO 
 WHERE JOB IN 'SALESMAN' 
 AND SAL > 1000;


 ---21) WAQTD ENAME ,LOC ,DNAME  AND SAL OF ALL THE DEPARTMENTS EVEN IN THAT THERE IS NO EMPLOYEES ARE WORKING AND LOC BELONGS TO NEW YORK ?
 SELECT ENAME, LOC, DNAME, SAL
 FROM EMP RIGHT JOIN DEPT 
 ON EMP.DEPTNO = DEPT.DEPTNO
 WHERE LOC IN 'NEW YORK';


 ---22) WAQTD ENAME ,LOC , AND DNAME ,HIREDATE  SAL OF ALL THE EMPLOYEES EVEN IF THEY NOT ASSIGNED TO ANY DEPARTMENT . WORKING AS SALESMAN AND WHOSE NAME STARTS WITH CONSONANTS  ?
 SELECT ENAME, LOC, DNAME, HIREDATE,SAL 
 FROM EMP LEFT JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
 WHERE JOB IN 'SALESMAN'
 AND NOT REGEXP_LIKE (ENAME,'^[A,E,I,O,U]','i');


 ---23) WAQTD ALL THE EMPLOYEES DETAILS AND THEIR DEPARTMENT DETAILS EVEN THE EMPLOYEES ARE NOT ASSIGNED TO ANY LOCATION IF DEPARTMENT NAME HAVING A CHARACTERS 
 SELECT * 
 FROM EMP RIGHT JOIN DEPT 
 ON EMP.DEPTNO = DEPT.DEPTNO
 WHERE DNAME LIKE '%A%';


 ---24) Display all trainers even if they have no students.
 SELECT TRAINER.* 
 FROM TRAINER LEFT JOIN STUDENT
 ON TRAINER.TRAINER_ID IN STUDENT.TRAINER_ID;


 ---25) Display all students even if trainer details are missing.
 SELECT STUDENT.* 
 FROM TRAINER RIGHT JOIN STUDENT
 ON TRAINER.TRAINER_ID = STUDENT.TRAINER_ID;


 ---26) Display trainers without students using LEFT JOIN.
 SELECT TRAINER.* 
 FROM TRAINER LEFT JOIN STUDENT
 ON TRAINER.TRAINER_ID = STUDENT.TRAINER_ID;


 ---27) Display students without trainers using RIGHT JOIN (if possible).
 SELECT STUDENT.*
 FROM TRAINER RIGHT JOIN STUDENT
 ON TRAINER.TRAINER_ID = STUDENT.TRAINER_ID;


 ---28) Display total trainers and total students together.
 SELECT * 
 FROM STUDENT LEFT JOIN TRAINER 
 ON STUDENT.TRAINER_ID = TRAINER.TRAINER_ID;


 ---29) Display students whose trainer earns maximum salary.
 SELECT S.STUDENT_NAME , T.TRAINER_NAME, T.SALARY
 FROM STUDENT S RIGHT JOIN TRAINER T
 ON S.TRAINER_ID = T.TRAINER_ID 
 WHERE T.SALARY IN (SELECT MAX(SALARY) FROM TRAINER);


 ---30) Display students who belong to the trainer having maximum experience
 SELECT S.STUDENT_NAME , T.TRAINER_NAME , T.SALARY 
 FROM STUDENT S RIGHT JOIN TRAINER T 
 ON S.TRAINER_ID = T.TRAINER_ID 
 WHERE EXPERIENCE_YRS = (SELECT MAX(EXPERIENCE_YRS) FROM TRAINER);
