---146).WAQTD NUMBER OF EMPLOYEES WORKING IN EACH DEPARTEMENT EXCEPT PRESIDENT. ?
SELECT COUNT (*) , JOB 
FROM EMP 
WHERE JOB NOT IN 'PRESIDENT'
GROUP BY JOB;


---147)WAQTD TOTAL SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH JOB. ?
SELECT SUM(SAL), JOB 
FROM EMP 
GROUP BY JOB ;


---148)WAQTD NUMBER OF EMPLOYEEES WORKING AS MANAGER IN EACH DEPARTMENT. ?
SELECT DEPTNO,COUNT(*)
FROM EMP 
WHERE JOB IN 'MANAGER'
GROUP BY DEPTNO;


---149).WAQTD AVG SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH DEPARTMENT EXCLUDING THE EMPLOYEES OF DEPTNO 20 . ? 
SELECT DEPTNO,AVG(SAL)
FROM EMP
WHERE DEPTNO NOT IN 20 
GROUP BY DEPTNO;


---150).WAQTD NUMBER OF EMPLOYEES HAVING CHARACTER 'A' IN THEIR NAMES IN EACH JOB.  ?
SELECT JOB,COUNT(*) 
FROM EMP 
WHERE ENAME LIKE '%A%'
GROUP BY JOB;


---151).WAQTD NUMBER OF EMPLOYEES AND AVG SALARY NEEDED TO PAY THE EMPLOYEES WHO SALARY IN GREATER THAN 2000 IN EACH DEPT. ?
SELECT DEPTNO , AVG(SAL), COUNT(*) 
FROM EMP 
WHERE SAL>2000
GROUP BY DEPTNO ;


---152)WAQT D TOTAL SALARY NEEDED TO PAY AND NUMBER OF SALESMANS IN EACH DEPT. ?
SELECT DEPTNO,SUM(SAL),COUNT(*)
FROM EMP 
WHERE JOB IN 'SALESMAN' 
GROUP BY DEPTNO;


---153)WAQTD NUMBER OF EMPLOYEES WITH THEIR MAXIMUM SALARIES IN EACH JOB. ?
SELECT JOB,COUNT(*),MAX(SAL)
FROM EMP 
GROUP BY JOB;


---154) WAQTD MAXIMUM SALARIES GIVEN TO AN EMPLOYEE WORKING IN EACH DEPT. ?
SELECT DEPTNO , MAX(SAL)
FROM EMP 
GROUP BY DEPTNO ;


---155)WAQTD NUMBER OF TIMES THE SALARIES PRESENT IN EMPLOYEE TABLE. ?
SELECT SAL,COUNT(*)
FROM EMP 
GROUP BY SAL;
