---131) WAQTD MAX SALARY FROM THE EMPLOYEE TABLE ?
SELECT MAX(SAL) 
FROM EMP ;


---132) WAQTD MAX AND MIN COMM FROM EMPLOYEES TABLE ?
SELECT MAX(COMM) , MIN(COMM) 
FROM EMP ;


---133) WAQTD TOTAL SALARY NEEDED TO PAY FOR THE SALESMAN ?
SELECT SUM(SAL)
FROM EMP 
WHERE JOB IN 'SALESMAN';


---134) WAQTD NUMBER OF EMPLOYEES WORKING IN DEPTNO 30 ?
SELECT COUNT(*) 
FROM EMP 
WHERE DEPTNO =30;


---135) WAQTD NUMBER OF EMPLOYEES WORKING AS MANAGER IN DEPTNO 20?
SELECT COUNT(*)
FROM EMP 
WHERE JOB IN 'MANAGER' AND DEPTNO IN 20 ;


---136) WAQTD MAX SALARY NEEDED TO PAY FOR THE EMPLOYEES WHOSE NAME STARTS WITH A ?
SELECT MAX(SAL)
FROM EMP 
WHERE ENAME LIKE 'A%';


---137) WAQTD AVG SALARY NEEDED TO PAY FOR THE EMPLOYEES OF DEPTNO 10 ?
SELECT AVG(SAL) 
FROM EMP 
WHERE DEPTNO IN 10 ;


---138) WAQTD TOTAL SALARY AND AVG SALARY NEEDED TO PAY FOR THE EMPLOYEES WHO ARE HIRED IN THE RANGE OF 81 TO 87 ?
SELECT SUM(SAL),AVG(SAL)
FROM EMP 
WHERE HIREDATE BETWEEN '01-JAN-81' AND '31-DEC-87';


---139) WAQTD NUMBER OF EMPLOYEES WORKING IN DEPTNO 40 ?
SELECT COUNT(*) 
FROM EMP 
WHERE DEPTNO IN 20;


---140) WAQTD TOTAL SALARY NEEDED TO PAY FOR THE EMPLOYEES WHO ARE REPORTING TO 7839 ?
SELECT SUM(SAL)
FROM EMP 
WHERE EMPNO = 7839;


---141) WAQTD HOW MANY EMPLOYEES ARE WORKIN AS PRESIDENT IN DEPTNO 10 AND EARNING SALARY MORE THEN 4000 ?
SELECT COUNT(*)
FROM EMP 
WHERE JOB IN 'PRESIDENT' AND DEPTNO IN 10 AND SAL >4000;


---142) WAQTD HOW MANY EMPLOYEES ARE WORKIN AS SALESMAN IN DEPTNO 30 AND EARNING SALARY LESS THEN 5000 ?
SELECT COUNT(*) 
FROM EMP 
WHERE JOB IN 'SALESMAN' AND DEPTNO IN 30 AND SAL<5000;


---143) WAQTD HOW MANAY EMPLOYEES ARE HIRED ON 03-DEC- 81 iN DEPTNO 10 , 20
SELECT COUNT (*) 
FROM EMP 
WHERE HIREDATE = '03-DEC-81' AND DEPTNO IN (10,20);


---144) WAQTD HOW MUCH TOTAL SALARY NEEDE TO PAY FOR THE EMPLOYEE WHOSE MAME HAVING A CHARACTER ?
SELECT SUM(SAL)
FROM EMP 
WHERE REGEXP_LIKE (ENAME, '.*A.*','i');


---145) WAQTD AVG SALARY NEEDED TO PAY FOR THE SALESMAN IN DEPTNO 30 ?
SELECT AVG(SAL)
FROM EMP 
WHERE JOB IN 'SALESMAN' AND DEPTNO IN 30 ;
