  ---166).WAQTD NAME OF THE EMPLOYEES EARNING MORE THAN ADAMS ?
  SELECT ENAME , SAL 
  FROM EMP 
  WHERE SAL > (SELECT SAL FROM EMP 
               WHERE ENAME IN 'ADAMS');


  ---167).WAQTD NAME AND SALARY OF THE EMPLOYEES EARNING LESS THAN KING
  SELECT ENAME , SAL 
  FROM EMP 
  WHERE SAL < (SELECT SAL FROM EMP 
                WHERE ENAME IN 'KING');


  ---168) WAQTD NAME AND DEPTNO OF THE EMPLOYEES IF THEY ARE WORKING IN THE SAME DEPT AS JONES
  SELECT ENAME , DEPTNO 
  FROM EMP 
  WHERE DEPTNO = (SELECT DEPTNO FROM EMP 
                   WHERE ENAME IN 'JONES');


  ---169) WAQTD NAME AND JOB OF ALL THE EMPLOYEES WORKING IN THE SAME DESIGNATION AS JAMES 
  SELECT ENAME , JOB 
  FROM EMP 
  WHERE JOB = (SELECT JOB FROM EMP 
                WHERE ENAME IN 'JAMES');


   --- 170)WAQTD EMPNO AND ENAME ALONG WITH ANNUAL SALARY OF ALL THE EMPLOYEES IF THEIR ANNUAL SALARY IS GREATER THAN WARDS ANNUAL SALARY.
  SELECT EMPNO , ENAME , SAL*12 "ANNUAL"
  FROM EMP 
  WHERE (SAL*12) > (SELECT SAL*12 FROM EMP 
                     WHERE ENAME IN 'WARD');


   --- 171) .WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED BEFORE SCOTT AND HIRED AFTER THE PRESIDENT ?
  SELECT ENAME , HIREDATE 
  FROM EMP 
  WHERE HIREDATE > (SELECT HIREDATE FROM EMP 
                     WHERE JOB IN 'PRESIDENT')
   AND HIREDATE < (SELECT HIREDATE FROM EMP 
                   WHERE ENAME IN 'SCOTT');


  ---172) .WAQTD NAME AND SAL OF THE EMPLOYEE IF THEY ARE EARNING SAL LESS THAN THE EMPLOYEE WHOS EMPNO IS 7839
  SELECT ENAME , SAL 
  FROM EMP 
  WHERE SAL < (SELECT SAL FROM EMP 
                WHERE EMPNO = 7839);


  ---173).WAQTD ALL THE DETAILS OF THE EMPLOYEES IF THE EMPLOYEES ARE HIRED BEFORE MILLER 
  SELECT * FROM EMP 
  WHERE HIREDATE < (SELECT HIREDATE FROM EMP 
                      WHERE ENAME IN 'MILLER');

 
  ---174) .WAQTD ENAME AND EMPNO OF THE EMPLOYEES IF EMPLOYEES ARE EARNING MORE THAN ALLEN
  SELECT ENAME , EMPNO FROM EMP 
  WHERE SAL > (SELECT SAL FROM EMP 
                 WHERE ENAME IN 'ALLEN');


  ---175).WAQTD ENAME AND SALARY OF ALL THE EMPLOYEES WHO ARE EARNING MORE THAN MILLER BUT LESS THAN ALLEN.
  SELECT ENAME , SAL FROM EMP 
  WHERE SAL > (SELECT SAL FROM EMP 
                 WHERE ENAME IN 'MILLER')
   AND SAL < (SELECT SAL FROM EMP 
                WHERE ENAME IN 'ALLEN');


  ---178).WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING IN DEPT 20 AND WORKING IN THE SAME DESIGNATION AS SMITH 
  SELECT * FROM EMP 
  WHERE DEPTNO IN 20 
  AND JOB IN (SELECT JOB FROM EMP 
               WHERE ENAME IN 'SMITH');


  ---179).WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE SAME DEPT AS TURNER
  SELECT * FROM EMP 
  WHERE JOB IN 'MANAGER' 
  AND DEPTNO = (SELECT DEPTNO FROM EMP 
                 WHERE ENAME IN 'TURNER');


  ---180).WAQTD NAME AND HIREDATE OF THE EMPLOYEES HIRED AFTER 1980 AND BEFORE KING 
  SELECT ENAME , HIREDATE FROM EMP 
  WHERE HIREDATE > '31-DEC-80' 
  AND HIREDATE < (SELECT HIREDATE FROM EMP 
                   WHERE ENAME IN 'KING');


  ---181).WAQTD ALL THE DETAILS OF EMPLOYEES WHO EARN MORE THAN SCOTT BUT LESS THAN KING
  SELECT * FROM EMP 
  WHERE SAL > (SELECT SAL FROM EMP 
                 WHERE ENAME IN 'SCOTT')
  AND SAL < (SELECT SAL FROM EMP 
                WHERE ENAME IN 'KING');


  ---182).WAQTD NAME OF THE EMPLOYEES WHOS NAME STARTS WITH 'A' AND WORKS IN THE SAME DEPT AS BLAKE 
  SELECT ENAME , DEPTNO 
  FROM EMP 
  WHERE ENAME LIKE 'A%' 
  AND DEPTNO IN (SELECT DEPTNO FROM EMP 
                    WHERE ENAME IN 'BLAKE');


   --- 183).WAQTD NAME AND COMM IF EMPLOYEES EARN COMMISSION AND WORK IN THE SAME DESIGNATION AS SMITH
  SELECT ENAME , COMM , JOB 
  FROM EMP 
  WHERE COMM IS NOT NULL
  AND JOB IN (SELECT JOB FROM EMP 
                 WHERE ENAME IN 'SMITH');


  ---184).WAQTD DETAILS OF ALL THE EMPLOYEES WORKING AS CLERK IN THE SAME DEPT AS TURNER.
  SELECT * FROM EMP 
  WHERE JOB IN 'CLERK'
  AND DEPTNO IN ( SELECT DEPTNO FROM EMP 
                  WHERE ENAME IN 'TURNER');


  ---185).WAQTD ENAME, SAL AND DESIGNATION OF THE EMPLOYEES WHOS ANNUAL SALARY IS MORE THAN SMITH AND LESS THAN KING.
  SELECT ENAME , SAL ,JOB 
  FROM EMP 
  WHERE (SAL*12) > (SELECT SAL*12 FROM EMP 
                     WHERE ENAME IN 'SMITH')
  AND (SAL*12) < (SELECT SAL*12 FROM EMP 
                   WHERE ENAME IN 'KING');

            
  --- 187).WAQTD DNAME AND LOC OF THE EMPLOYEE WHOS
  ENAME IS KING 
  SELECT DNAME FROM DEPT 
    WHERE DEPTNO IN (SELECT DEPTNO FROM EMP 
                     WHERE ENAME IN ('SMITH' , 'KING'));


   --- 188).WAQTD LOC OF THE EMP WHOS EMPLOYEE NUMBER IS 7902
  SELECT LOC FROM DEPT 
  WHERE DEPTNO = (SELECT DEPTNO FROM EMP 
                    WHERE EMPNO = 7902);


  --- 189) WAQTD DNAME AND LOC ALONG WITH DEPTNO OF THE EMPLOYEE WHOS NAME ENDS WITH 'R'.
  SELECT DNAME , LOC 
  FROM DEPT 
  WHERE DEPTNO IN (SELECT DEPTNO FROM EMP 
                    WHERE ENAME LIKE '%R');


  ---190) .WAQTD DNAME OF THE EMPLOYEE WHOS DESIGNATION IS PRESIDENT
  SELECT DNAME FROM DEPT 
  WHERE DEPTNO IN (SELECT DEPTNO FROM EMP 
                     WHERE JOB IN 'PRESIDENT');


  --- 191) .WAQTD NAMES OF THE EMPLOYEES WORKING IN ACCOUNTING DEPARTMENT
  SELECT ENAME FROM EMP 
  WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT 
                     WHERE DNAME IN 'ACCOUNTING');


  --- 192) .WAQTD ENAME AND SALARIES OF THE EMPLOYEES WHO ARE WORKING IN THE LOCATION CHICAGO
  SELECT ENAME , SAL FROM EMP 
  WHERE DEPTNO IN ( SELECT DEPTNO FROM DEPT 
                      WHERE LOC IN 'CHICAGO');


  ---193). WAQTD DETAILS OF THE EMPLOYEES WORKING IN SALES 
  SELECT * FROM EMP 
  WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT
                     WHERE DNAME IN 'SALES');


  --- 194) .WAQTD DETAILS OF THE EMP ALONG WITH ANNUAL SALARY IF EMPLOYEES ARE WORKING IN NEW YORK
  SELECT EMP.* , SAL*12 "ANNUAL" 
  FROM EMP 
  WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT 
                    WHERE LOC IN 'NEW YORK');

 
  ---195) .WAQTD NAMES OF THE EMPLOYEES EARNING MORE THAN SCOTT IN ACCOUNTING DEPT
  SELECT ENAME , SAL , DEPTNO 
  FROM EMP 
  WHERE SAL>ALL (SELECT SAL FROM EMP 
                  WHERE ENAME IN 'SCOTT')
  AND DEPTNO IN (SELECT DEPTNO FROM DEPT 
                WHERE DNAME IN 'ACCOUNTING');


  ---196). WAQTD DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE LOCATION CHICAGO 
  SELECT * FROM EMP 
  WHERE JOB IN 'MANAGER' 
  AND DEPTNO IN (SELECT DEPTNO FROM DEPT 
                  WHERE LOC IN 'CHICAGO');


  ---197) .WAQTD NAME AND SAL OF THE EMPLOYEES EARNING MORE THAN KING IN THE DEPT ACCOUNTING
  SELECT ENAME , SAL , SAL , DEPTNO 
  FROM EMP 
  WHERE SAL > (SELECT SAL FROM EMP 
                WHERE ENAME IN 'KING')
  AND DEPTNO IN (SELECT DEPTNO FROM DEPT 
                   WHERE DNAME IN 'ACCOUNTING');


  ---198) .WAQTD DETAILS OF THE EMPLOYEES WORKING AS SALESMAN IN THE DEPARTEMENT SALES 
  SELECT * FROM EMP 
  WHERE JOB IN 'SALESMAN' AND 
  DEPTNO IN (SELECT DEPTNO FROM DEPT 
              WHERE DNAME IN 'SALES');


  ---199) .WAQTD NAME, SAL. JOB, HIREDATE OF THE EMPLOYEES WORKING IN OPERATIONS DEPARTMENT AND HIRED BEFORE KING
  SELECT ENAME , SAL , JOB ,HIREDATE 
  FROM EMP 
  WHERE HIREDATE < (SELECT HIREDATE FROM EMP 
                     WHERE ENAME IN 'KING')
  AND DEPTNO IN (SELECT DEPTNO FROM DEPT 
                 WHERE DNAME IN 'OPERATIONS');


  ---200) .DISPLAY ALL THE EMPLOYEES WHOSE DEPARTMET NAMES ENDING 'S'.
  SELECT * FROM EMP 
  WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT 
                     WHERE DNAME LIKE '%S');


  ---201) .WAQTD DNAME OF THE EMPLOYEES WHOS NAMES HAS CHARACTER 'A' IN IT.
  SELECT DNAME FROM DEPT 
  WHERE DEPTNO IN (SELECT DEPTNO FROM EMP
                    WHERE ENAME LIKE '%A%');


  ---202) . WAQTD DNAME AND LOC OF THE EMPLOYEES WHOS SALARY IS RUPEES 800. 
  SELECT DNAME , LOC FROM DEPT 
  WHERE DEPTNO IN (SELECT DEPTNO FROM EMP 
                    WHERE SAL IN 800);


  ---203) .WAQTD DNAME OF THE EMPLOYEES WHO EARN COMISSION
  SELECT DNAME FROM DEPT 
  WHERE DEPTNO IN (SELECT DEPTNO FROM EMP 
                    WHERE COMM IS NOT NULL);


  ---204) .WAQTD LOC OF THE EMPLOYEES IF THEY EARN COMISSION IN DEPT 40
  SELECT LOC , DEPTNO FROM DEPT 
  WHERE DEPTNO IN 40 
  AND DEPTNO IN (SELECT DEPTNO FROM EMP 
                  WHERE COMM IS NOT NULL);

