 ---205) .WAQTD NAME OF THE EMPLOYEES EARNING SALARY MORE THAN THE SALESMAN
 SELECT ENAME , SAL , JOB 
 FROM EMP 
 WHERE SAL > ALL (SELECT SAL FROM EMP 
                  WHERE JOB IN 'SALESMAN');


 ---206) WAQTD DETAILS OF THE EMPLOYEES HIRED AFTER ALL THE CLERKS
 SELECT * FROM EMP 
 WHERE HIREDATE > ALL (SELECT HIREDATE FROM EMP 
                       WHERE JOB IN 'CLERK');


 --- 208) WAQTD NAME AND HIREDATE OF EMPLOYEES HIRED BEFORE ALL THE MANAGERS
 SELECT ENAME , HIREDATE FROM EMP 
 WHERE HIREDATE < ALL (SELECT MIN(HIREDATE) FROM EMP 
                    WHERE JOB IN 'MANAGER');


 ---209) .WAQTD NAMES OF THE EMPLOYEES HIRED AFTER ALL THE MANAGERS AND EARNING SALARY MORE THAN
 ALL THE CLERKS
 SELECT ENAME , HIREDATE , SAL 
 FROM EMP 
 WHERE HIREDATE > ALL (SELECT MAX(HIREDATE) FROM EMP 
                       WHERE JOB IN 'MANAGER')
 AND SAL >ALL (SELECT MAX(SAL) FROM EMP 
              WHERE JOB IN 'CLERK');


 ---210) .WAQTD DETAILS OF THE EMPLOYEES WORKING AS CLERK AND HIRED BEFORE ATLEST A SALESMAN 
 SELECT * FROM EMP 
 WHERE JOB IN 'CLERK'
 AND HIREDATE < ALL (SELECT MAX(HIREDATE) FROM EMP 
                        WHERE JOB IN 'SALESMAN');


 --- 211).WAQTD DETAILS OF EMPLOYEES WORKING IN ACCOUNTING OR SALES DEPT
 SELECT * FROM EMP 
 WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT 
                  WHERE DNAME IN ('SALES' , 'ACCOUNTING'));


 ---212) WAQTD DEPARTMENT NAMES OF THE EMPOYEES WITH NAME SMITH, KING AND MILLER
 SELECT DNAME , DEPTNO 
 FROM DEPT 
 WHERE DEPTNO IN (SELECT DEPTNO FROM EMP 
                  WHERE ENAME IN ('SMITH', 'KING' , 'MILLER'));


 ---213) .WAQTD DETAILS OF EMPLOYEES WORKING NEWYORK OR CHICAGO
 SELECT * FROM EMP 
 WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT 
                  WHERE DNAME IN 'NETWORK' OR LOC IN 'CHICAGO');


 ---214)  WAQTD EMP NAMES IF EMPLOYEES ARE HIRED AFTER ALL THE EMPLOYEES OF DEPT 10
 SELECT ENAME , HIREDATE , DEPTNO 
 FROM EMP 
 WHERE HIREDATE > ALL (SELECT MAX(HIREDATE) FROM EMP 
                       WHERE DEPTNO IN 10 );
