--- Q11) WAQTD EMPLOYEES NAME FROM EMPLOYEES TABLE ?
SELECT ENAME 
FROM EMP;


--- Q12) WAQTD SAL AND EMPLOYEES NAME FROM EMPLOYEE TABLE ?
SELECT SAL , ENAME 
FROM EMP ;


--- Q13) WAQTD NAME AND DEPTNO AND JOBS THAT ARE PRESENT IN EMP TABLE ?
SELECT ENAME , DEPTNO, JOB 
FROM EMP ;


--- Q14) WAQTD HIREDATE AND DEPTNO FOR ALL THE EMPLOYEES ?
SELECT HIREDATE, DEPTNO
FROM EMP;


--- Q15) WAQTD MGR AND EMPNO FROM EMPLOYEE TABLE ?
SELECT MGR, EMPNO
FROM EMP;


--- Q16) WAQTD ALL THE DETAILS OF ALL THE EMPLOYEES ?
SET LINES 20000 PAGES 20000
SELECT * FROM EMP;


--- Q17) WAQTD DEPARTMENT NAME FROM DEPT TABLE ?
SELECT DNAME 
FROM DEPT;


--- Q18) WAQTD LOC THAT ARE PRESENT IN DEPT TABLE
SELECT LOC 
FROM DEPT;


--- Q19) WAQTD DEPTNO AND LOC PRESENT IIN DEPT TABLE ?
SELECT DEPTNO , LOC 
FROM DEPT;


--- Q20) WAQTD ALL THE DETAILS OF DEPT TABLE ? 
SELECT * FROM DEPT;


--- Q21) WAQTD DIFFERENT JOBS PRESENT IN EMPLOYEE TABLE ?
SELECT DISTINCT JOB 
FROM EMP ;


--- Q22) WAQTD ENAME AND SAL PRESENT IN EMP TABLE BUT THERE SHOULD NOT BE ANY REPEATED RECORDS ?
SELECT DISTINCT ENAME , SAL 
FROM EMP;


--- Q23) WAQTD HIREDATE AND SAL OF AN EMPLOYEES BUT THERE SHOULD NOT BE ANY REPEATED RECORDS ?
SELECT DISTINCT HIREDATE , SAL 
FROM EMP;


--- Q24) WAQTD JOB SAL AND DEPTNO OF AN EMPLOYEES BUT THERE SHOULD NOT BE ANY REPEATED RECORDS ?
SELECT DISTINCT JOB , SAL, DEPTNO 
FROM EMP;


--- Q25) WAQTD ALL THE DETAILS OF AN EMPLOYEES BUT THERE SHOULD NOT BE ANY REPEATED RECORDS ?
SELECT DISTINCT * FROM EMP;


--- Q26) WAQTD ANNUAL SALARY FOR ALL THE EMPLOYEES ?
SELECT SAL*12 "ANNUAL SALARY" 
FROM EMP;


--- Q27) WAQTD HALF TERM SALARY FOR ALL THE EMPLOYEES ?
SELECT SAL*6 "HALF-TERM SAL" FROM EMP;


--- Q28) WAQTD ENAME AND ANNUAL SALARY FOR ALL THE EMPLOYEES ?
SELECT ENAME , SAL * 12 "ANNUAL SAL"
FROM EMP;


--- Q29) WAQTD DEPTNO JOB AND SAL WITH 10% HIKE FOR ALL THE EMPLOYEE ?
SELECT DEPTNO, JOB, SAL, SAL+SAL*10/100 "10% HIKE" 
FROM EMP;

 
--- Q30) WAQTD ALL THE DETAILS OF AN EMPLOYEES ALONG WITH ANNUAL SALARY ?
SELECT EMP.* , SAL* 12 "ANNUAL SAL"
FROM EMP;


--- Q31) WAQTDALL THE DETAILS OF AN EMPLOYEES ALONG WITH 10% HIKE IN ANNUAL SALARY FOR ALL THE EMPLOYEE ?
SELECT EMP.*, SAL+SAL*10/100 "10% HIKE"
FROM EMP;


--- Q32) WAQTD SAL ANNAUL SALARY HALF_TERM SALARY AND QUERTER TERM SALARY FOR ALL THE EMPLOYEES ?
SELECT SAL, SAL*12 "ANNUAL SAL", SAL*6 "HALF-TERM", SAL*3 "QUARTER-TERM"
FROM EMP;


--- Q33) WAQTD ANNUAL SALARY WITH 20% DEDUCTION  FOR ALL THE EMPLOYEES ?
SELECT SAL*12 "ANNUAL SAL", (SAL-SAL*12/100)*12 "20% DEDUCTION"
FROM EMP;


--- Q34) WAQTD ALL THE DETAILS ALONG WITH 100 RS PENALTY FOR ALL THE EMPLOYEES ?
SELECT EMP.*, SAL-100 "PENALTY" 
FROM EMP;


--- Q36) WAQTD ANNAUL SALARY  AND HALF_TERM SALARY WITH ALIAS NAME FOR ALL THE EMPLOYEES ?
SELECT SAL* 12 "ANNUAL SAL", SAL*6 "HALF_TERM"
FROM EMP;


--- Q37) WAQTD ALL THE DETAILS OF AN EMPLOYEES ALONG WITH 12% HIKE IN ANNUAL SALARY WITH ALIAS NAME FOR ALL THE EMPLOYEES 
SELECT EMP.*, (SAL+SAL*12/100)*12 "12%_HIKE" 
FROM EMP;


--- Q38) WAQTD JOB AS DESIGNATION HIREDATE AS JOINING DATE MGR AS REPORTING MANAGER NUMBER FOR ALL THE EMPLOYEES ?
SELECT JOB AS DESIGNATION, HIREDATE "JOINING DATE", MGR AS "REPORTING MANAGER NUMBER"
FROM EMP;


--- Q39) WAQTD JOB  WITH DEPTNO FOR ALL THE EMPLOYEES USING ALIAS ASDESIGNATION FOR THE JOB AND DNO FOR THE DEPTNO ?
SELECT JOB "DESIGNATION", DEPTNO "DNO"
FROM EMP;


--- Q40) WAQTD ALL THE DETAILS OF AN EMPLOYEES ALONG WITH 50 RS HIKE IN SAL USE ALIAS AS BONUS FOR ALL THE EMPLOYEE ?
SELECT EMP.*, SAL+50 "BONUS"
FROM EMP;

