---41 ) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHOSE SALARY IS MORE THEN 1000 ?
SELECT *
FROM EMP
WHERE SAL>1000;


---42) WAQTD ENAME AND SALARY FOR THE EMPLOYEES WHOSE DEPTNO IS 20 ?
SELECT ENAME,SAL
FROM EMP
WHERE DEPTNO = 20;


---43) WAQTD JOB AND DEPTNO OF AN EMPLOYEES WHO ARE  WORKING AS MANAGER ?
SELECT JOB, DEPTNO 
FROM EMP 
WHERE JOB = 'MANAGER';


---44) WAQTD ALL THE DETAILS OF ALL THE EMPLOYEES WHOSE NAME IS KING ?
SELECT * 
FROM EMP 
WHERE ENAME = 'KING';


---45) WAQTD NAME AND HIREDATE OF ALL THE EMPLOYEES WHO HIRED ON ‘01-JAN-81 ?
SELECT ENAME,HIREDATE 
FROM EMP 
WHERE HIREDATE = '01-JAN-81';


---46) WAQTD HIREDATE AND DEPTNO OF AN EMPLOYEES WHO HIRED AFTER THE 1981 ?
SELECT HIREDATE , DEPTNO 
FROM EMP 
WHERE HIREDATE >= '01-JAN-82';


---47) WAQTD ALL THE DETAILS OF AN EMPLOYEES WHO HIRED BEFORE THE 1987 ?
SELECT * 
FROM EMP 
WHERE HIREDATE < '01-JAN-87';


---48) WAQTD ALL THE DETAILS ALONG WITH ANNUAL SALARY FOR ALL THE EMPLOYEES WHOSE SAL IS LESS THEN 5000 ?
SELECT EMP.*, SAL*12 "ANNUAL_SAL" 
FROM EMP 
WHERE SAL<5000;


---49) WAQTD ALL THE DETAILS OF AN EMPLOYEES WHOSE  JOB IS MANAGER ?
SELECT * FROM EMP 
WHERE JOB = 'MANAGER';


---50) WAQTD ENAME AND JOB AND DEPTNO OF ALL THE EMPLOYEES WHO ARE WORKING IN DEPTNO 30 ?
SELECT ENAME, JOB , DEPTNO 
FROM EMP 
WHERE DEPTNO = 30;


---51) WAQTD ALL THE DETAILS OF AN EMPLOYEES WHOSE JOB IS NOT SALESMAN ?
SELECT * FROM EMP 
WHERE JOB <> 'SALESMAN';


---52) WAQTD ENAME AND JOB OF ALL THE EMPLOYEES EXCEPT THE EMPLOYEES OF DEPTNO 20 ?
SELECT ENAME , JOB 
FROM EMP 
WHERE DEPTNO != 20;


---53) WAQTD JOB EPTNO AND SAL OF AN ALL THE EMPLOYEES EXCEPT THE EMPLOYEES WHO ARE WORKING AS SALESMAN ?
SELECT JOB , DEPTNO ,SAL 
FROM EMP 
WHERE JOB <> 'SALESMAN';


---54) WAQTD DESIGNATION OF ALL THE EMPLOYEES EXCEPT KING ?
SELECT ENAME , JOB 
FROM EMP 
WHERE ENAME <> 'KING';


---55) WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH THAT 20% HIKE OF IN THEIR SALARY FOR THE EMPLOYEES WHO HIRED AFTER 85 ?
SELECT EMP.*, SAL+SAL*20/100 "20%_HIKE"
FROM EMP 
WHERE HIREDATE > '31-DEC-85';


---56) WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH THAT 12% DEDUCTION  OF IN THEIR SALARY FOR THE EMPLOYEES WHO HIRED BEFORE  84 ?
SELECT EMP.*, SAL-SAL*12/100 "12%_DEDUCT" 
FROM EMP 
WHERE HIREDATE < '01-JAN-84';


---57) WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH THAT 2000 BONUS  OF IN THEIR SALARY FOR THE EMPLOYEES WHOSE EMPNO IS 7369 ?
SELECT EMP.*, SAL+2000 "BONUS"
FROM EMP 
WHERE EMPNO = 7369;


---58) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE NOT WORKING IN  DEPTNO 10 ?
SELECT * 
FROM EMP 
WHERE DEPTNO <> 10 ;


---59) WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH HALFTERM SALARY FOR ALL THE EMPLOYEE WHOSE ANNUAL SALARY IS MORE THEN 14000 ?
SELECT * 
FROM ( SELECT EMP.*, SAL*6 "HALF_TERM", SAL*12 "ANNUAL" FROM EMP )
WHERE ANNUAL>14000;


---60) WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH THAT 20% HIKE OF IN THEIR  HALF TERM SALARY FOR ALL THE EMPLOYEES WHOSE HALF TERM SALARY IS MORE THAN 7000 ?
SELECT * 
WHERE HALF_TERM > 7000;

